MKSHELL=/bin/bash

## This virtual order takes a vcf file, and splits the body using UNIX 'split' command
%.SPLITVCF:QV: %.body.tmp %.header.tmp
	echo "[DEBUG] splitting vcf file"
	split \
		--suffix-length=7 \
		-d \
		--elide-empty-files \
		--number=l/$NUMBER_OF_CHUNKS \
		$stem.body.tmp \
		$stem.chunk \
	&& for chunk in $stem.chunk*
	do
		echo "[DEBUG] reheading $chunk"
		cat $stem.header.tmp $chunk > $chunk.vcf \
		&& rm $chunk
	done \
	&& rm $stem.*.tmp

%.body.tmp:Q: %.vcf.bgz
	echo "[DEBUG] extracting body"
	bcftools view -H $prereq > $target.build \
	&& mv $target.build $target

%.header.tmp:Q: %.vcf.bgz
	echo "[DEBUG] extracting header"
	bcftools view -h $prereq > $target.build \
	&& mv $target.build $target
