MKSHELL=/bin/bash

## target:OPTIONS: prereq
%.PASSfiltered.vcf:Q: %.vcf.bgz
	echo "[DEBUG] filtering variants"
	zcat $prereq \
	| awk '
		BEGIN {FS=OFS="\t"}
		$1 ~ /^#/ { print $0 }
		$7=="PASS" { print $0 }
	' > $target.build \
	&& mv $target.build $target
