MKSHELL=/bin/bash

## target:OPTIONS: prereq
%.PASSfiltered.vcf:Q: %.vcf
	echo "[DEBUG] filtering variants"
 	bcftools view --apply-filters PASS $prereq > $target.build \
	&& mv $target.build $target
