MKSHELL=/bin/bash

## edit a vcf file to:
# 1. (bcftools annotate --remove LIST) remove some anotations from the fields: use a fields_to_remove.txt file to control this
# 2. (bcftools annotate --rename-chrs file) change chr names from 1,2,3... to chr1,chr2,chr3...: use a  map in file, with "old_name new_name\n" pairs separated by whitespaces, each on a separate line.
%.edited.vcf:Q: %.vcf
	echo "[DEBUG] editing vcf"
	## transform column format in fields_to_remove.txt to comma separated list
	# IMPORTANT: lines starting wiht # WILL BE removed from the fields
	bcftools annotate \
		--remove $(grep "^#" fields_to_remove.txt | tr -d "#" | tr "\n" "," | sed "s#,\$##") \
		--rename-chrs chr_synonyms.txt \
	$prereq > $target.build \
	&& mv $target.build $target
